### ISSUE TITLE
Error with grant

### ISSUE THREAD

**Issue by renatocassino** [clexmond/omniauth-disqus#1]
I'm trying to use this lib and I'm getting this error.

```
OAuth2::Error: invalid_grant: Invalid parameter: redirect_uri (values for POST and GET arguments differ)\n{\"error_description\":\"Invalid parameter: redirect_uri (values for POST and GET arguments differ)\",\"error\":\"invalid_grant
```

I'm using omniauth with Facebook too, and with facebook works.
The redirect_uri is equals to my local.

Full error stack

```
Started GET "/auth/disqus/" for 127.0.0.1 at 2018-06-03 11:11:13 -0300
I, [2018-06-03T11:11:13.527280 #21352]  INFO -- omniauth: (disqus) Request phase initiated.
Started GET "/auth/disqus/callback?state=5a82b0c016a2e8385813fb27ac74437ddd880e07489247fe&code=13a489e332894ed9b04dc204b7a16a4f" for 127.0.0.1 at 2018-06-03 11:11:16 -0300
I, [2018-06-03T11:11:16.520938 #21352]  INFO -- omniauth: (disqus) Callback phase initiated.
E, [2018-06-03T11:11:16.940125 #21352] ERROR -- omniauth: (disqus) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: Invalid parameter: redirect_uri (values for POST and GET arguments differ)
{"error_description":"Invalid parameter: redirect_uri (values for POST and GET arguments differ)","error":"invalid_grant"}
  
OAuth2::Error (invalid_grant: Invalid parameter: redirect_uri (values for POST and GET arguments differ)
{"error_description":"Invalid parameter: redirect_uri (values for POST and GET arguments differ)","error":"invalid_grant"}):
  
oauth2 (1.4.0) lib/oauth2/client.rb:119:in `request'
oauth2 (1.4.0) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.4.0) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
```

Could you help me?

**Comment by clexmond** [comment]
Resolved by https://github.com/clexmond/omniauth-disqus/issues/1
